-- 1. Create table for tracking unique views (logs)
create table if not exists post_view_logs (
  id bigint generated by default as identity primary key,
  post_id text not null,
  viewer_hash text not null,
  created_at timestamptz default now()
);

-- 2. Add unique index to prevent duplicate views from same viewer for same post
-- This ensures one view per hash per post forever.
-- If you want "unique daily views", you could include date_trunc('day', created_at) in the index.
create unique index if not exists idx_unique_post_viewer on post_view_logs(post_id, viewer_hash);

-- 3. Create optimized function to register view safely
create or replace function register_view(p_post_id text, p_viewer_hash text)
returns boolean
language plpgsql
security definer
as $$
declare
  is_new_view boolean;
begin
  -- Try to insert into logs
  begin
    insert into post_view_logs (post_id, viewer_hash)
    values (p_post_id, p_viewer_hash);
    is_new_view := true;
  exception when unique_violation then
    is_new_view := false;
  end;

  -- If it was a new view, increment the main counter
  if is_new_view then
    insert into post_views (post_id, view_count, last_updated)
    values (p_post_id, 1, now())
    on conflict (post_id)
    do update set 
      view_count = post_views.view_count + 1,
      last_updated = now();
  end if;

  return is_new_view;
end;
$$;
