
-- Profiles Table (for extended profile data)
create table if not exists profiles (
  wallet_address text primary key,
  bio text,
  website text,
  location text,
  banner_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Follows Table
create table if not exists follows (
  id bigint generated by default as identity primary key,
  follower text not null,
  following text not null,
  created_at timestamptz default now(),
  unique(follower, following)
);

-- Bookmarks Table
create table if not exists bookmarks (
  id bigint generated by default as identity primary key,
  user_address text not null,
  post_id text not null,
  creator_address text,
  timestamp bigint,
  created_at timestamptz default now(),
  unique(user_address, post_id)
);

-- Tips Table
create table if not exists tips (
  id bigint generated by default as identity primary key,
  sender text not null,
  receiver text,
  amount bigint not null,
  timestamp bigint not null,
  hash text not null,
  post_id text,
  type text default 'sent',
  created_at timestamptz default now()
);

-- Notifications Table
create table if not exists notifications (
  id uuid default gen_random_uuid() primary key,
  user_address text not null,
  message text not null,
  type text default 'info',
  timestamp bigint not null,
  read boolean default false,
  related_user text,
  created_at timestamptz default now()
);

-- Votes Table
create table if not exists votes (
  id bigint generated by default as identity primary key,
  post_id text not null,
  creator_address text not null,
  user_address text not null,
  vote_type text not null check (vote_type in ('up', 'down')),
  created_at timestamptz default now(),
  unique(post_id, user_address)
);

-- Enable Row Level Security (RLS) is recommended but currently API handles checks
-- Ideally, you should enable RLS and add policies for public read / authenticated write.
